language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - 195703@edu.p.lodz.pl
      - 195568@edu.p.lodz.pl
      - 199184@edu.p.lodz.pl
      - 195662@edu.p.lodz.pl